# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch from Github
      uses: actions/checkout@v2
      

    - name: Maven Compile
      run: mvn compile
        
    - name: Maven Test
      run: mvn test
      
    - name: Have Github actions build whole project - test, compile and wrap into .jar
      run: mvn -B package --file pom.xml
